spring:
  application:
    name: eureka


---
spring:

  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://${username}:${password}@localhost:9000
  security:
    username: ${security_username}
    password: ${security_password}
---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://${secrets.username}:${secrets.password}@config-server:9000
  security:
    username: ${secrets.security_username}
    password: ${secrets.security_password}


